title: "My CTF Writeups"
description: "Exploit journeys, reversing notes, pwn breakdowns."
markdown: kramdown
highlighter: rouge

# Site navigation links
nav:
  - name: Home
    link: /
  - name: Writeups
    link: /#writeups
  - name: About
    link: /about

# Show future posts? (turn on if you prepare drafts)
future: false
